name: waffart
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Routing
  go_router: ^16.3.0
  go_router_guards: ^2.0.0+2
  sentry_flutter: ^9.10.0

  # Backend
  supabase_flutter: ^2.5.0
  hive_flutter: ^1.1.0

  # Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # UI
  cached_network_image: ^3.4.1
  intl: ^0.20.3
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10

  # Utils
  connectivity_plus: ^6.1.5
  shared_preferences: ^2.5.5
  logger: ^2.7.0
  dartz: ^0.10.1
  flutter_dotenv: ^6.0.1
  firebase_crashlytics: ^4.3.10
  equatable: ^2.1.0
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^17.2.4
  permission_handler: ^11.4.0
  http: ^1.6.0
  flutter_inappwebview: ^6.1.5
  webview_flutter: ^4.14.1
  fl_chart: ^0.68.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  riverpod_generator: ^2.6.4
  mockito: ^5.4.6
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/.env
    - assets/.env.development
    - assets/.env.staging
    - assets/.env.production
