# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true

# AndroidX
android.useAndroidX=true
android.enableJetifier=false

# Built-in Kotlin / new DSL
android.builtInKotlin=false
android.newDsl=false

# حل مشكلة "different roots" على Windows
kotlin.incremental=false
org.gradle.caching=false

android.user.home=C\:\\Users\\mhass\\.android

# ملاحظة: لا تحدد org.gradle.java.home هنا
# خلي Gradle يكتشف الـ JDK تلقائيًا من Android Studio أو JAVA_HOME